# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_auto_20181026_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'images/'),
        ),
    ]
